#!/usr/bin/env python3
"""Generate src/image_dat.h from the game's images.dat / images.tbl / *.grp files.

The click model (gary_env's clickable rectangle = union of clickable images' GRP frames) needs,
per image type: whether it is clickable (images.dat `is_clickable`) and each frame's offset and
size inside the GRP (the GRP file header). Column layout is images.dat's file format as loaded by
external/openbw/data_loading.h (load_images_dat); file names resolve through images.tbl; the GRP
frame table layout is read_grp's (bwgame.h): u16 frames, u16 width, u16 height, then per frame
u8 x, y, w, h + u32 data offset. Inputs come from resim/extract_gamedata.cpp (gitignored).

Usage: python tools/gen_image_dat.py [--out src/image_dat.h]
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SCR = REPO / "data" / "gamedata" / "scr"

# images.dat column order (data_loading.h load_images_dat): (name, unit size, count)
COLUMNS = [
    ("grp_filename_index", 4, 999),
    ("has_directional_frames", 1, 999),
    ("is_clickable", 1, 999),
    ("has_iscript_animations", 1, 999),
    ("always_visible", 1, 999),
    ("modifier", 1, 999),
    ("color_shift", 1, 999),
    ("iscript_id", 4, 999),
    ("shield_filename_index", 4, 999),
    ("attack_filename_index", 4, 999),
    ("damage_filename_index", 4, 999),
    ("special_filename_index", 4, 999),
    ("landing_dust_filename_index", 4, 999),
    ("lift_off_filename_index", 4, 999),
]


def read_columns(data: bytes) -> dict[str, list[int]]:
    off = 0
    out: dict[str, list[int]] = {}
    for name, size, count in COLUMNS:
        n = size * count
        chunk = data[off:off + n]
        if len(chunk) != n:
            raise SystemExit(f"images.dat truncated at {name}: need {n}, got {len(chunk)}")
        fmt = {1: "B", 4: "I"}[size]
        out[name] = list(struct.unpack("<" + fmt * count, chunk))
        off += n
    return out


def read_tbl(data: bytes) -> list[str]:
    n = struct.unpack_from("<H", data, 0)[0]
    offs = struct.unpack_from("<" + "H" * n, data, 2)
    names = []
    for o in offs:
        end = data.index(b"\0", o)
        names.append(data[o:end].decode("ascii", "replace"))
    return names


def read_grp(data: bytes) -> tuple[int, int, list[tuple[int, int, int, int]]]:
    """(width, height, [(x, y, w, h)] per frame) per read_grp's file layout."""
    frames, w, h = struct.unpack_from("<HHH", data, 0)
    table = []
    for i in range(frames):
        x, y, fw, fh, _off = struct.unpack_from("<BBBB I", data, 6 + i * 8)
        table.append((x, y, fw, fh))
    return w, h, table


def main() -> None:
    out = REPO / "adapters" / "scr_bridge" / "src" / "image_dat.h"
    for i, a in enumerate(sys.argv):
        if a == "--out":
            out = Path(sys.argv[i + 1])
    cols = read_columns((SCR / "arr" / "images.dat").read_bytes())
    names = read_tbl((SCR / "arr" / "images.tbl").read_bytes())
    clickable = cols["is_clickable"]
    grp_idx = cols["grp_filename_index"]
    # per type: grp canvas (w,h), then frames flattened; kImageFramesOff[t] indexes the flat array
    canvas = [(0, 0)] * 999
    frames_off = [0] * 1000
    flat: list[tuple[int, int, int, int]] = []
    missing = 0
    for t in range(999):
        frames_off[t] = len(flat)
        gi = grp_idx[t]
        if gi < len(names):
            # tbl names are relative to the game's unit\ directory (extract: data/gamedata/scr/unit)
            path = SCR / "unit" / names[gi].replace("\\", "/")
            if path.exists() and path.suffix.lower() == ".grp":
                w, h, tbl = read_grp(path.read_bytes())
                canvas[t] = (w, h)
                flat.extend(tbl)
                continue
        missing += 1
        flat.append((0, 0, 0, 0))
    frames_off[999] = len(flat)
    print(f"image types: 999, frames: {len(flat)}, missing grp files: {missing}")
    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_image_dat.py from images.dat / images.tbl / *.grp (do not edit).",
        "// Per image type: clickable bit (images.dat is_clickable), GRP canvas size, and each",
        "// frame's (x, y, w, h) inside the GRP (GRP file frame table, read_grp layout).",
        "#include <cstdint>",
        "",
        "namespace garyscr {",
        "",
        "constexpr uint8_t kImageClickable[999] = {",
    ]
    for i in range(0, 999, 16):
        lines.append("    " + ", ".join("1" if clickable[j] else "0"
                                        for j in range(i, min(i + 16, 999))) + ",")
    lines += ["};", "", "constexpr uint16_t kImageGrpSize[999][2] = {"]
    for i, (w, h) in enumerate(canvas):
        lines.append(f"    {{{w}, {h}}},  // {i}")
    lines += ["};", "", "constexpr uint16_t kImageFramesOff[1000] = {"]
    for i in range(0, 1000, 16):
        lines.append("    " + ", ".join(str(frames_off[j]) for j in range(i, min(i + 16, 1000))) + ",")
    lines += ["};", "", "constexpr uint8_t kImageFrames[][4] = {"]
    for x, y, w, h in flat:
        lines.append(f"    {{{x}, {y}, {w}, {h}}},")
    lines += ["};", "", "}  // namespace garyscr", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()