#!/usr/bin/env python3
"""Generate src/unit_dat.h (placement sizes in tiles) from the game's own units.dat.

The column layout is units.dat's file format as loaded by external/openbw/data_loading.h
(load_units_dat: the `rawr` column order and element sizes). Input is the extracted game data
in data/gamedata/scr/arr/units.dat (resim/extract_gamedata.cpp produced it; gitignored).

Usage: python tools/gen_unit_dat.py [path/to/units.dat] [--out src/unit_dat.h]
"""
from __future__ import annotations

import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]

# (name, value size, values per entry, count) in units.dat column order (data_loading.h
# load_units_dat; xy fields read 2 values and rect fields 4 values per type).
COLUMNS = [
    ("flingy", 1, 1, 228), ("turret_unit_type", 2, 1, 228), ("subunit2", 2, 1, 228),
    ("infestation_unit", 2, 1, 96), ("construction_animation", 4, 1, 228),
    ("unit_direction", 1, 1, 228), ("has_shield", 1, 1, 228), ("shield_points", 2, 1, 228),
    ("hitpoints", 4, 1, 228), ("elevation_level", 1, 1, 228), ("unknown1", 1, 1, 228),
    ("sublabel", 1, 1, 228), ("computer_ai_idle", 1, 1, 228), ("human_ai_idle", 1, 1, 228),
    ("return_to_idle", 1, 1, 228), ("attack_unit", 1, 1, 228), ("attack_move", 1, 1, 228),
    ("ground_weapon", 1, 1, 228), ("max_ground_hits", 1, 1, 228), ("air_weapon", 1, 1, 228),
    ("max_air_hits", 1, 1, 228), ("ai_internal", 1, 1, 228), ("flags", 4, 1, 228),
    ("target_acquisition_range", 1, 1, 228), ("sight_range", 1, 1, 228),
    ("armor_upgrade", 1, 1, 228), ("unit_size", 1, 1, 228), ("armor", 1, 1, 228),
    ("right_click_action", 1, 1, 228), ("ready_sound", 2, 1, 106),
    ("first_what_sound", 2, 1, 228), ("last_what_sound", 2, 1, 228),
    ("first_pissed_sound", 2, 1, 106), ("last_pissed_sound", 2, 1, 106),
    ("first_yes_sound", 2, 1, 106), ("last_yes_sound", 2, 1, 106),
    ("placement_size", 2, 2, 228),   # xy: x, y per type
    ("addon_position", 2, 2, 96),    # xy over buildings (offset 106)
    ("dimensions", 2, 4, 228),       # rect: x0, y0, x1, y1 per type
    ("portrait", 2, 1, 228), ("mineral_cost", 2, 1, 228), ("gas_cost", 2, 1, 228),
    ("build_time", 2, 1, 228), ("unknown2", 2, 1, 228), ("group_flags", 1, 1, 228),
    ("supply_provided", 1, 1, 228), ("supply_required", 1, 1, 228),
    ("space_required", 1, 1, 228), ("space_provided", 1, 1, 228),
    ("build_score", 2, 1, 228), ("destroy_score", 2, 1, 228),
    ("unit_map_string_index", 2, 1, 228), ("is_broodwar", 1, 1, 228),
    ("staredit_availability_flags", 2, 1, 228),
]


def read_columns(data: bytes) -> dict[str, list[int]]:
    off = 0
    out: dict[str, list[int]] = {}
    for name, size, per, count in COLUMNS:
        n = size * per * count
        chunk = data[off:off + n]
        if len(chunk) != n:
            raise SystemExit(f"units.dat truncated at {name}: need {n}, got {len(chunk)}")
        fmt = {1: "B", 2: "H", 4: "I"}[size]
        out[name] = list(struct.unpack("<" + fmt * (per * count), chunk))
        off += n
    if off != len(data):
        raise SystemExit(f"units.dat has {len(data) - off} trailing bytes (column layout wrong)")
    return out


def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    src = Path(args[0]) if args else REPO / "data" / "gamedata" / "scr" / "arr" / "units.dat"
    out = REPO / "adapters" / "scr_bridge" / "src" / "unit_dat.h"
    for i, a in enumerate(sys.argv):
        if a == "--out":
            out = Path(sys.argv[i + 1])
    cols = read_columns(src.read_bytes())
    raw = cols["placement_size"]  # flat x,y,x,y...
    xy = [(raw[i], raw[i + 1]) for i in range(0, len(raw), 2)]
    # The DAT stores the placement box in pixels (OpenBW divides by 32 to get tiles:
    # external/openbw/ui/ui.h) — normalise to whole tiles either way.
    scale = 32 if max(max(v) for v in xy) >= 16 else 1
    tiles = [(max(1, x // scale), max(1, y // scale)) for x, y in xy]
    for t, name in ((106, "CommandCenter"), (109, "SupplyDepot"), (111, "Barracks"),
                    (131, "Hatchery"), (154, "Nexus"), (156, "Pylon")):
        print(f"{name}({t}): {tiles[t][0]}x{tiles[t][1]} tiles")
    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_unit_dat.py from the game's units.dat (do not edit by hand).",
        "// Placement box in tiles, [w, h] per unit type (0 = not placeable).",
        "#include <cstdint>",
        "",
        "namespace garyscr {",
        "",
        "constexpr uint8_t kPlacementSize[228][2] = {",
    ]
    for i, (x, y) in enumerate(tiles):
        lines.append(f"    {{{x}, {y}}},  // {i}")
    lines += ["};", "", "}  // namespace garyscr", ""]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
